# Generated by Django 4.0.4 on 2022-07-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_category_news_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_of_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال به کانال تلگرام'),
        ),
    ]
