# Generated by Django 4.0.4 on 2022-07-01 14:52

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_date_of_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.upload_image_path, verbose_name='تصویر'),
        ),
    ]
