# Generated by Django 4.0.4 on 2022-07-06 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(related_name='user_team', to=settings.AUTH_USER_MODEL, verbose_name='اعضا'),
        ),
    ]
