# Generated by Django 4.0.4 on 2022-07-06 07:47

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.utils.upload_image_path, verbose_name='لوگو')),
                ('main_job', models.TextField(verbose_name='کار استارت آپ')),
                ('date_of_formation', models.DateTimeField(verbose_name='تاریخ تشکیل')),
            ],
            options={
                'verbose_name': 'استارت آپ',
                'verbose_name_plural': 'استارت آپ ها',
                'ordering': ['id'],
                'base_manager_name': 'objects',
            },
        ),
    ]
