# Generated by Django 4.0.4 on 2022-07-03 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startup', '0002_alter_startup_ceo'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='user',
            field=models.ManyToManyField(related_name='user_startup', to=settings.AUTH_USER_MODEL, verbose_name='اعضا'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='ceo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_startup', to=settings.AUTH_USER_MODEL, verbose_name='مدیر عامل'),
        ),
    ]
