# Generated by Django 4.0.4 on 2022-07-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_startup_user_alter_startup_ceo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='ceo',
        ),
    ]
