# Generated by Django 4.0.4 on 2022-07-04 12:44

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_manager',
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('owner_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('owner_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'startup'), ('model', 'startup')), models.Q(('app_label', 'team'), ('model', 'team')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='team_content_type', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='user.customgroup', verbose_name='groups'),
        ),
    ]
