# Generated by Django 4.0.4 on 2022-06-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='editor',
            new_name='is_editor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='team_manager',
            new_name='is_team_manager',
        ),
    ]
