# Generated by Django 4.0.4 on 2022-07-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_editor_user_is_editor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_editor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_team_manager',
        ),
    ]
