# Generated by Django 4.0.4 on 2022-07-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0003_alter_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='owner_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'startup'), ('model', 'startup')), models.Q(('app_label', 'team'), ('model', 'team')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='owner_group_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='owner_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
