# Generated by Django 4.0.4 on 2022-07-04 06:42

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0003_remove_user_is_editor_remove_user_is_team_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('team_object_id', models.PositiveIntegerField()),
                ('startup_object_id', models.PositiveIntegerField()),
                ('startup_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_content_type', to='contenttypes.contenttype')),
                ('team_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_content_type', to='contenttypes.contenttype')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='user.customgroup', verbose_name='groups'),
        ),
    ]
