# Generated by Django 4.0.4 on 2022-07-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customgroup_alter_user_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
    ]
