# Generated by Django 4.0.4 on 2022-07-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0005_alter_customgroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='startup_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='startup_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='team_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='team_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
