# Generated by Django 4.0.4 on 2022-07-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0009_alter_customgroup_startup_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='startup_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('team.Team', 'startup.Startup')}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_content_type', to='contenttypes.contenttype'),
        ),
    ]
