# Generated by Django 4.0.4 on 2022-07-04 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0011_alter_customgroup_startup_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgroup',
            old_name='startup_object_id',
            new_name='owner_object_id',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='startup_content_type',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='team_content_type',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='team_object_id',
        ),
        migrations.AddField(
            model_name='customgroup',
            name='owner_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'startup'), ('model', 'startup')), models.Q(('app_label', 'team'), ('model', 'team')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_content_type', to='contenttypes.contenttype'),
        ),
    ]
