# Generated by Django 4.0.4 on 2022-06-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product_team', to='team.product'),
        ),
    ]
