# Generated by Django 4.0.4 on 2022-07-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_product_description_alter_team_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
