# Generated by Django 4.0.4 on 2022-07-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_remove_team_product_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='date',
            field=models.DateTimeField(verbose_name='سال ساخت'),
        ),
    ]
