# Generated by Django 4.0.4 on 2022-07-05 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0006_alter_team_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(related_name='user_team', to=settings.AUTH_USER_MODEL, verbose_name='اعضا'),
        ),
    ]
